### ISSUE TITLE
Woodland edge expansion

### ISSUE THREAD

**Issue by C0S1N3** [soldag/forest-shuffle-scoring#1]
![woodlands](https://github.com/user-attachments/assets/0e21d36b-aa60-45bb-82ef-8f74522bf1ad)
Could you please add the scoring of woodland edge expansion?
Here is the cards:(https://x.boardgamearena.net/data/themereleases/current/games/forestshuffle/240905-1103/img/woodlands.Jpg)

**Comment by soldag** [comment]
Of course, I didn't noticed that all the cards are already available. I'm currently on vacation, but I'll get to it once I'm back.

**Comment by soldag** [comment]
Finally got some time to implement the new expansion. It's live now.
